version: "3.8"

services:
    db:
        image: mysql:${MYSQL_VERSION}
        container_name: wp-db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
          - "${DB_LOCAL_PORT}:3306"
        volumes:
            - ./vol-db:/var/lib/mysql
        networks:
            - wp-network

    wordpress:
        depends_on:
          - db
        image: wordpress:${WP_VERSION}-php${PHP_VERSION}-fpm-alpine
        container_name: wp
        restart: unless-stopped
        volumes:
            - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./vol-wp:/var/www/html
        environment:
            WORDPRESS_DB_HOST: ${DB_HOST}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_USER: ${DB_USERNAME}
            WORDPRESS_DB_NAME: ${DB_NAME}
            WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
            WORDPRESS_DEBUG: ${WP_DEBUG}
        networks:
            - wp-network

    cli:
        build:
            args:
                wp_url: ${WP_URL}
                wp_user: ${WP_USER}
                wp_password: ${WP_PASSWORD}
                wp_email: ${WP_EMAIL}
                wp_timezone: ${WP_TIMEZONE}
                wp_lang: ${WP_LANG}
                wp_title: ${WP_TITLE}
                wp_description: ${WP_DESCRIPTION}
                wp_debug: ${WP_DEBUG}
                wp_theme: ${WP_THEME}
                wp_plugins: ${WP_PLUGINS}
            context: ./wp-cli
            dockerfile: Dockerfile
        image: wpcli
        container_name: wp-cli
        restart: unless-stopped
        depends_on:
            - db
        volumes_from:
          - wordpress
        volumes:
            - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            WORDPRESS_DB_HOST: ${DB_HOST}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_USER: ${DB_USERNAME}
            WORDPRESS_DB_NAME: ${DB_NAME}
            WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
            WORDPRESS_DEBUG: ${WP_DEBUG}
        networks:
            - wp-network

    nginx:
        depends_on:
          - wordpress
        image: nginx:${NGINX_VERSION}-alpine
        container_name: wp-nginx
        restart: unless-stopped
        ports:
            - ${HTTP_LOCAL_PORT}:80
            - ${HTTPS_LOCAL_PORT}:443
        volumes_from:
          - wordpress
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - wp-network

networks:
    wp-network:
        driver: bridge
